spring.application.name=SpringEcom
spring.datasource.url=jdbc:postgresql://localhost:5432/Ecom
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update